# frozen_string_literal: true

module PublicProductVersions
  ##
  # === Get Products.
  # Get a collection of products.
  #
  # ==== Parameters
  # options:: (Hash) -- List of {Resource collection Options}[#class-Mints::Pub-label-Resource+collections+options+] shown above can be used as parameter.
  # use_post:: (Boolean) -- Variable to determine if the request is by 'post' or 'get' functions.
  #
  # ==== First Example
  #     @data = @mints_pub.get_product_versions
  #
  # ==== Second Example
  #     options = { fields: "title" }
  #     @data = @mints_pub.get_product_versions(options)
  #
  # ==== Third Example
  #     options = { fields: "title" }
  #     @data = @mints_pub.get_product_versions(options, false)
  def get_product_versions(options = nil, use_post = true)
    get_query_results('/ecommerce/product-versions', options, use_post)
  end

  ##
  # === Get Product.
  # Get a single product.
  #
  # ==== Parameters
  # slug:: (String) -- It's the string identifier generated by Mints.
  # options:: (Hash) -- List of {Single Resource Options}[#class-Mints::Pub-label-Single+resource+options] shown above can be used as parameter.
  #
  # ==== First Example
  #     @data = @mints_pub.get_product_version("product_slug")
  #
  # ==== Second Example
  #     options = {
  #       fields: 'id, slug'
  #     }
  #     @data = @mints_pub.get_product_version("lego-set", options)
  def get_product_version(slug, options = nil)
    @client.raw('get', "/ecommerce/product-versions/#{slug}", options)
  end
end
